### ISSUE TITLE
Missing Keyword in PackingEnv 'KeyError: 'action_mask''

### ISSUE THREAD

**Issue by karrtik-kmp** [luisgarciar/3D-bin-packing#16]
code snapshot in src/packing_env.py:
```
  import warnings
  import os
  import sys
  
  p_dir = os.path.split(os.getcwd())[0]
  if p_dir not in sys.path:
      sys.path.append(p_dir)
  
  warnings.filterwarnings("ignore", category=DeprecationWarning)
  # Environment initialization
  register(id="PackingEnv-v0", entry_point="src.packing_env:PackingEnv")
  
  env = make(
      "PackingEnv-v0",
      new_step_api=False,
      container_size=[11, 11, 11],
      box_sizes=boxes_generator([10, 10, 10], num_items=80, seed=5),
      num_visible_boxes=1,
      render_mode="rgb_array",
  )
  
  # Run the random agent without saving the gif
  obs = env.reset()
  images = []
  for step_num in range(80):
      action_mask = obs["action_mask"]
      action = env.action_space.sample(action_mask)
      obs, reward, done, info = env.step(action)
      print(step_num)
      if done:
          break

```
After calling env.reset() we are not getting action_mask key values

Error 1:
```
Traceback (most recent call last):
  File "D:\Work\Company Product Brainstorming\Packing\3D-bin-packing\A_newbranch\3D-bin-packing\tests\profile_script.py", line 46, in <module>
    action_mask = obs["action_mask"]
KeyError: 'action_mask'

```
And if it is modified to include it into fir into state i am not getting correct format.

Error2:
```
Traceback (most recent call last):
  File "D:\Work\Company Product Brainstorming\Packing\3D-bin-packing\A_newbranch\3D-bin-packing\tests\profile_script.py", line 47, in <module>
    action = env.action_space.sample(action_mask)
TypeError: Discrete.sample() takes 1 positional argument but 2 were given

```

please someone can help me ..

**Comment by chengchegn** [comment]
Hello, have you solved this error1? I also encountered the same problem.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[3], [line 18](vscode-notebook-cell:?execution_count=3&line=18)
     [16](vscode-notebook-cell:?execution_count=3&line=16) fig = env.render()
     [17](vscode-notebook-cell:?execution_count=3&line=17) gif.create_image(fig)
---> [18](vscode-notebook-cell:?execution_count=3&line=18) action_mask = obs['action_mask']
     [20](vscode-notebook-cell:?execution_count=3&line=20) action = env.action_space.sample(action_mask)
     [21](vscode-notebook-cell:?execution_count=3&line=21) obs, reward, done, info = env.step(action)

KeyError: 'action_mask'

**Comment by luisgarciar** [comment]
Could you provide a minimal code example to reproduce the error?
